### ISSUE TITLE
install_github("dkidney/gibbonsecr") gives Error in read.dcf(path)

### ISSUE THREAD

**Issue by Brakels** [dkidney/gibbonsecr#1]
I cannot install the gibbonsecr package.

the error message shows: Error in read.dcf(path) : 
  Found continuation line starting '    person("Darren", ...' at begin of record.

What do you suggest me to do.

I am on Windows and using the latest version of R studio (1.1.463) and R 3.5.2

**Comment by dkidney** [comment]
Hi, thanks for letting me know - I've added a develop branch on which the issue should now be fixed. Please try the code below:

`devtools::install_github("dkidney/gibbonsecr", ref = "develop")`

**Comment by Brakels** [comment]
Ok, i am mange to launch it.

gui()

All good now. I am curious to try it out.

**Comment by Brakels** [comment]
When importing the data , i receive an error message saying "Double counted
groups"  (the detection data file) .

But in the example of the manual (.csv file) the groups are also double
counted during different occasions.

Could you please have a look at my data? see file attached

**Comment by Brakels** [comment]
All good now again sorry.. i removed the double counted groups...

**Comment by Brakels** [comment]
Setting the model parameters

I am not sure how to reliably estimate the g0, sigma and the bearings parameter. Do you have a some suggestion on which parameter to use in my case (multi-day survey, 4 occasions)? Its not mentioned in the manual either.

I estimated the pcall already which is 0.5179
